services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
      
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
#      - "80:80"
      - "10000:10000"
  dist001:
    image: distsession
    container_name: dist001
    hostname: dist001
    environment:
      - ConnectionStrings:RedisConnection=redis:6379
    build:
      context: .
      dockerfile: Dockerfile
  dist002:
    image: distsession
    container_name: dist002
    hostname: dist002
    environment:
      - ConnectionStrings:RedisConnection=redis:6379
    build:
      context: .
      dockerfile: Dockerfile
  dist003:
    image: distsession
    container_name: dist003
    hostname: dist003
    environment:
      - ConnectionStrings:RedisConnection=redis:6379
    build:
      context: .
      dockerfile: Dockerfile
